### ISSUE TITLE
availability on CRAN and/or conda

### ISSUE THREAD

**Issue by nick-youngblut** [abbyyan3/BhGLM#3]
I know that `BhGLM` and the associated manuscript is relatively new, but I was wondering whether the package will be made available on CRAN and/or conda anytime in the near future. My research lab uses conda for software installation/management, which greatly helps with data analysis reproducibility. Some of us are interested in using `BhGLM`, but the lack of availability on CRAN/conda makes it hard to integrate BhGLM into our bioinformatics software management setup.

Sorry if BhGLM is already on CRAN and/or conda and I've just missed it.

**Comment by abbyyan3** [comment]
Thank you for the interest. Sorry, it is not available in CRAN and it is under development. I will keep you updated. 

Best,
